openapi: 3.0.0

info:

  title: JOBS-API

  description: 'TODO: Add Description'

  contact: {}

  version: '1.0'

servers:

- url: https://temp-jobs-api-nsw2.onrender.com/api/v1

  variables: {}

paths:

  /auth/login:

    post:

      tags:

      - Auth

      summary: Login User

      operationId: LoginUser

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security: []

  /auth/register:

    post:

      tags:

      - Auth

      summary: Register User

      operationId: RegisterUser

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security: []

  /jobs:

    get:

      tags:

      - Jobs

      summary: Get Jobs

      operationId: GetJobs

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

    post:

      tags:

      - Jobs

      summary: Create Job

      operationId: CreateJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID

    patch:

      tags:

      - Jobs

      summary: Update Job

      operationId: UpdateJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

    delete:

      tags:

      - Jobs

      summary: Delete Job

      operationId: DeleteJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

    get:

      tags:

      - Jobs

      summary: Get Single Job

      operationId: GetSingleJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

components:

  securitySchemes:

    httpBearer:

      type: http

      scheme: bearer

security:

- httpBearer: []

tags:

- name: Auth

  description: ''

- name: Jobs

  description: ''

